### ISSUE TITLE
how to set custom title

### ISSUE THREAD

**Issue by romariorobby** [Baldomo/open-in-mpv#14]
Hi, how could i set custom flag `--title=`? i've tried on the following example and append `--title=titlename` but it doesn't worked.

```yaml
---
players:
  mpv:
    name: mpv
    executable: mpv
    fullscreen: "--fs"
    pip: "--ontop --no-border --autofit=384x216 --geometry=98\\%:98\\%" # --title=titlename ( not worked)
    enqueue: ""
    new_window: ""
    needs_ipc: true
    flag_overrides: {} 
    # "*": "--title=titlename" (this too)
```
