### ISSUE TITLE
bug: open-in-mpv can not read config 

### ISSUE THREAD

**Issue by toprak** [Baldomo/open-in-mpv#18]
### Bug Description

Hi, I installed open-in-mpv with _git clone and sudo make install , make install-protocol._ I created a config file which is **~/.config/open-in-mpv/config.yml** I also added it to **/etc/xdg/open-in-mpv/** I also changed the configuration file before doing _sudo make install , make install-protocol_ but problem is still, when I click the open-in-mpv on firefox to some youtube links it does not read my configuration file. I even tried install with precompiled binaries

### How to Reproduce

1. Go to 'youtube.com'
2. Click on 'open-in-mpv'
3. Do 'wait'
4. See 'default settings'

### Expected Behavior

I expected to execute umpv which is executable script for mpv, it makes mpv unique application so I can add videos to playlist with open-in-mpv extension, without having more mpv tabs, also it is expected to open mpv in fullscreen

### Version

firefox extension version 2.1.0  and app version 2.1.0

### Configuration

```yml
players:
  mpv:
    name: mpv
    executable: umpv
    fullscreen: "--fs"
    pip: ""
    enqueue: "--enqueue"
    new_window: ""
    needs_ipc: true
    supported_protocols: ["http", "https"]
    flag_overrides: {}
```

### What browsers are you seeing the problem on? (optional)

Firefox-based (Librewolf, Iceraven, etc.)

### Checklist:

- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.
