### ISSUE TITLE
bug: Launching with Celluloid launches both mpv and celluloid

### ISSUE THREAD

**Issue by yigib** [Baldomo/open-in-mpv#21]
### Bug Description

Choosing Celluloid as the player and clicking the icon results in both mpv and Celluloid launching, both playing the video.

### How to Reproduce

1. Go to settings and choose Celluloid
2. Open any youtube video
3. Click on the extension icon
4. See both players launching

### Expected Behavior

Only celluloid should be launching.

### Version

nightly (master branch)

### Configuration

```yml
players:
  mpv:
    name: mpv
    executable: mpv
    fullscreen: "--fs"
    pip: "--ontop --no-border --autofit=384x216 --geometry=98\\%:98\\%"
    enqueue: ""
    new_window: ""
    needs_ipc: true
    flag_overrides: {}
  celluloid:
    name: Celluloid
    executable: celluloid
    fullscreen: ""
    pip: ""
    enqueue: "--enqueue"
    new_window: "--new-window"
    needs_ipc: false
    flag_overrides: 
      "*": "--mpv-%s"
  mpvnet:
    name: mpv.net
    executable: mpvnet.exe
    fullscreen: "--fs"
    pip: "--ontop --no-border --autofit=384x216 --geometry=98\\%:98\\%"
    enqueue: "--queue"
    new_window: ""
    needs_ipc: false
    flag_overrides: {}
```

### Checklist:

- [x] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.
