### ISSUE TITLE
Browser extensions will not open MPV on PopOS. 

### ISSUE THREAD

**Issue by robbhimself** [Baldomo/open-in-mpv#27]
### Bug Description

On PopOS with both chrome and firefox, the extension will not open mpv. The xdg-open dialog box appears and you click "open in open-in-mpv" and nothing happens.

mpv works fine from terminal and playing youtube videos with mpv works fine.

### How to Reproduce

1. Go to 'youtube'
2. Click on 'open in mpv from the extension menu or the right click menu
3. Click "open in open-in-mpv" from the xdg-open dialog
4. See 'nothing happens :('

### Expected Behavior

Open mpv when you click "open in open-in-mpv" from the xdg-open dialog

### Version

2.2.0

### Configuration

```yml
players:
  mpv:
    name: mpv
    executable: mpv
    fullscreen: "--fs"
    pip: "--ontop --no-border --autofit=384x216 --geometry=98\\%:98\\%"
    enqueue: ""
    new_window: ""
    needs_ipc: true
    flag_overrides: {}
```

### Relevant log output (optional)

```sh
ive tried the precompiled binaries and compiled from git, the install-protocol.sh copies files to the right paths. Just nothing happens when the browser calls mpv.
```

### What browsers are you seeing the problem on? (optional)

Firefox-based (Librewolf, Iceraven, etc.), Chromium-based (Brave, Chrome, etc.)

### Checklist:

- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.
