### ISSUE TITLE
open-in-mpv has totally stop to work in any circumstance and on almost any site

### ISSUE THREAD

**Issue by MR-Diamond** [Baldomo/open-in-mpv#42]
### Bug Description

POST-EDIT: similar to this old issue: https://github.com/Baldomo/open-in-mpv/issues/41
If I execute `xdg-open 'mpv:///open?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdQw4w9WgXcQ&player=mpv'`
open-in-mpv, works.
If I go on a certain video site (I can't link it here, since is for adult only), open-in-mpv, works.
I executed various time the command `xdg-mime default open-in-mpv.desktop x-scheme-handler/mpv`, then I went in the Firefox settings, in the preferred applications sections: there were two mpv elements: this one: 

![Image](https://github.com/user-attachments/assets/b53f3c3f-60d1-43da-bfa4-c1e04356dc73)

And another one which I deleted, but if I correctly recall, was yt-dlp - mpv. I delete this one, executed again `xdg-mime default open-in-mpv.desktop x-scheme-handler/mpv` and now open-in-mpv works again also on youtube. So, in some way, the culprit was Firefox, and I had no idea why i had such `yt-dlp - mpv` I close this ticket, sorry for the noise.

_____________________________________________________________________________________________________________________
Firefox 136.0
open-in-mpv 2.4.3

As I go on any video streaming site (youtube, but also any other video streaming site, which on open-in-mpv has always worked), open-in-mpv doesn't work at all; when I click in the context menu or if I click on the icon of open-in-mpv in the panel.

I tried to execute open-in-mpv in terminal, eg:

`open-in-mpv https://www.youtube.com/watch?v=WiDhsLjKLy8`

I get:

```
2025/03/11 08:35:27 Player 'mpv' has no schemas, setting to defaults
2025/03/11 08:35:27 Player 'Celluloid' has no schemas, setting to defaults
2025/03/11 08:35:27 Player 'mpv.net' has no schemas, setting to defaults
2025/03/11 08:35:27 Unsupported protocol: https

```

The error `Unsupported protocol:` occurs also if I use http or omit at all the protocol: open-in-mpv no longer works.

### How to Reproduce

1. Go to youtube.com or on any other video streaming website
2. Click on the icon on the panel or in the context menu 
3 Nothing happen

### Expected Behavior

Expected Behavior:
should play the videos as before.

### Version

2.4.3

### Configuration

```yml
players:
  mpv:
    name: mpv
    executable: mpv
    fullscreen: "--fs"
    pip: "--ontop --no-border --autofit=384x216 --geometry=98\\%:98\\%"
    enqueue: ""
    new_window: ""
    needs_ipc: true
    flag_overrides: {}
  celluloid:
    name: Celluloid
    executable: celluloid
    fullscreen: ""
    pip: ""
    enqueue: "--enqueue"
    new_window: "--new-window"
    needs_ipc: false
    flag_overrides: 
      "*": "--mpv-%s"
  mpvnet:
    name: mpv.net
    executable: mpvnet.exe
    fullscreen: "--fs"
    pip: "--ontop --no-border --autofit=384x216 --geometry=98\\%:98\\%"
    enqueue: "--queue"
    new_window: ""
    needs_ipc: false
    flag_overrides: {}
```

### Relevant log output (optional)

```sh

```

### What browsers are you seeing the problem on? (optional)

Firefox-based (Librewolf, Iceraven, etc.)

### Checklist:

- [x] I have checked for existing issues that describe my problem prior to opening this one.
- [x] I understand that improperly formatted bug reports may be closed without explanation.
