### ISSUE TITLE
bug: opening with Celluloid isn't working

### ISSUE THREAD

**Issue by arthsmn** [Baldomo/open-in-mpv#43]
### Bug Description

Switched the option to open in Celluloid, tried opening a video and it doesn't even call Celluloid.

### How to Reproduce

1. Switch the option from mpv to Celluloid
2. Try opening a video by right-clicking

### Expected Behavior

It would open the video on Celluloid

### Version

v2.4.3

### Configuration

```yml
players:
  mpv:
    name: Celluloid
    executable: celluloid
    fullscreen: "--fs"
    pip: "--ontop --no-border --autofit=384x216 --geometry=98\\%:98\\%"
    needs_ipc: true
    flag_overrides: {}
```

### Relevant log output (optional)

```sh

```

### What browsers are you seeing the problem on? (optional)

Chromium-based (Brave, Chrome, etc.)

### Checklist:

- [x] I have checked for existing issues that describe my problem prior to opening this one.
- [x] I understand that improperly formatted bug reports may be closed without explanation.
